### ISSUE TITLE
READMEからリンクされている動画を見ることができない

### ISSUE THREAD

**Issue by nekketsuuu** [wbap/lis#20]
README.md から "Sample scene result movie" というテキストでリンクされているURL https://www.youtube.com/watch?v=7Ein1hRUQ_U にある動画を見ようとすると「この動画は再生できません」となります。公開の設定が異なるのではないでしょうか。

**Comment by rondelion** [comment]
私の環境からだと特に問題なく再生できました。

**Comment by nekketsuuu** [comment]
@rondelion 今確認したら見れるようになっていました。原因がよく分かりませんが、どなたかが直してくださったのかもしれません。ご報告ありがとうございます。
